export { default as TagsInputRoot } from './TagsInput.vue'
export { default as UiTagsInputInput } from './TagsInputInput.vue'
export { default as UiTagsInputItem } from './TagsInputItem.vue'
export { default as UiTagsInputItemDelete } from './TagsInputItemDelete.vue'
export { default as UiTagsInputItemText } from './TagsInputItemText.vue'export { default as TagsInputInput } from './TagsInputInput.vue'
export { default as TagsInputItem } from './TagsInputItem.vue'
export { default as TagsInputItemDelete } from './TagsInputItemDelete.vue'
export { default as TagsInputItemText } from './TagsInputItemText.vue'
