export { default as TableRoot } from './Table.vue'
export { default as UiTableBody } from './TableBody.vue'
export { default as UiTableCaption } from './TableCaption.vue'
export { default as UiTableCell } from './TableCell.vue'
export { default as UiTableEmpty } from './TableEmpty.vue'
export { default as UiTableFooter } from './TableFooter.vue'
export { default as UiTableHead } from './TableHead.vue'
export { default as UiTableHeader } from './TableHeader.vue'
export { default as UiTableRow } from './TableRow.vue'export { default as TableBody } from './TableBody.vue'
export { default as TableCaption } from './TableCaption.vue'
export { default as TableCell } from './TableCell.vue'
export { default as TableEmpty } from './TableEmpty.vue'
export { default as TableFooter } from './TableFooter.vue'
export { default as TableHead } from './TableHead.vue'
export { default as TableHeader } from './TableHeader.vue'
export { default as TableRow } from './TableRow.vue'
